application: synonymly
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
-   url: /tweet/english/beginner
    script: main.app
    login: admin
-   url: /tweet/english/intermediate
    script: main.app
    login: admin
-   url: /tweet/english/advanced
    script: main.app
    login: admin

libraries:
-   name: webapp2
    version: "2.5.2"