application: synonymly
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
-   url: /tweet/.*
    script: main.app
    login: admin

libraries:
-   name: webapp2
    version: "2.5.2"